---
ID: "2a62ddd9-1676-5088-9b6f-6026ba38cf8f"
Parent: "0ca4fff6-36cc-5bae-b41c-5ef9e5ce3f4d"
Template: "0ca4fff6-36cc-5bae-b41c-5ef9e5ce3f4d"
Path: "/sitecore/templates/Project/jss-nextjs-tpe/Styleguide-RouteFields/__Standard Values"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20221225T074157Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\JssImport
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "7137fcf1-a4bb-435e-b7d3-351e398236e9"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\JssImport
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20221225T074157Z
