---
ID: "23991bfb-d4c9-54b0-ab41-f318d2db789f"
Parent: "c19f0ef3-ec39-5467-98fd-27e2252bd5fa"
Template: "c19f0ef3-ec39-5467-98fd-27e2252bd5fa"
Path: "/sitecore/templates/Project/jss-nextjs-tpe/GraphQL-ConnectedDemo/__Standard Values"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20221225T074156Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\JssImport
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "61cb26b0-3838-4b34-97d7-c358c15a6247"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\JssImport
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20221225T074156Z
