---
ID: "bc7e556c-dfef-5cd5-970c-795656ee89fb"
Parent: "5de7ccca-b771-56cd-b358-c3dc46d931bb"
Template: "5de7ccca-b771-56cd-b358-c3dc46d931bb"
Path: "/sitecore/templates/Project/jss-nextjs-tpe/Styleguide-FieldUsage-File/__Standard Values"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20221225T074154Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\JssImport
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "edcb853a-47f8-4cfc-9a1f-c65de8296aa8"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\JssImport
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20221225T074154Z
